### ISSUE TITLE
Unable to Open Database File

### ISSUE THREAD

**Issue by Zer0-Official** [zerozedsc/Python-Point-Of-Sale-System#2]
When I run the program, it gives me an error.
![Screenshot (1)](https://user-images.githubusercontent.com/62067365/126721668-abfeba7f-e185-433d-af9f-2813c95686b8.png)

**Comment by zerozedsc** [comment]
Thank you for looking at my project. I'm sorry that **I forgot to change the database path on server.py.** I already fix it, you can try to clone my repo again. **I fix the path to sqlite3.db**. _Thank you again for issuing this to me_
